language: node_js
node_js: 10
install: npm install
script:
- npm run test
deploy:
  provider: heroku
  on:
    repo: djq99/LRU-Cache
    branches:
      only:
      - master
  app: my-cache
  api_key:
    secure: RyJ7i0GASz8HHIJlq9e2ePF7QtCHzAGgzRk0y5H6p4PMts+XNqg3xoZhXaqUH65kzrvwvdUx5ZLFAYTTA9BeLgO5WxQm38Eh/0EUsdJL1CutnAv8QA8Ut8DvIZKAfLFdhnKJIa7Ww+R+vrPuZ0XXId8A4eKd7cY6OF2NdhlE6eAQYQPINJjW9GKmhu6kD/Cgh8T8JudtxQ+1jZJE4PqunP0XTE6P5h8Xkx5plU5Eb1dHu2QZgKQLi9x3KQzhyuWjRGx82GQHSMsqnTenofI6CPXGaj0W4TcWh9D/JTQmgaM8iMCe7qXbGZLfABCNmKYnYYCVCadsEN2z1zDkOdxslUHJVgSK5C17KmqxxwzNri2RmiJWlkOGwqc3uJeHcYOWFvzujmYWebUgv+6IlXRIP/Oy6Pg3NF7YtxTNgEb/aB9uir+n+E1gVaQgt1O/yxpofMT6u+vrv7n6e0z9csxjGjJ8GVhP7PtDXbITDOjxwOdGzQHt6lq5gfVQhthb4wIVpSS2OUFEfzz8KJLPJJHMt6NdlRI8z2vEzcZ1ghyPTNxmCPG4QoJH1mschrrpnV9lwY5O7nddrqpUfPs3RNTVibdrQu9PSpuHZkNkO7KnL7Ipdy3mQw+b16caWeSzCfG5NHUo5FpTs+Uo/CwHELJhlgiQ/gkboiZSCXAuWx0jhXo=
